### ISSUE TITLE
Install fails -> ModuleNotFoundError: No module named 'jupyter_server'

### ISSUE THREAD

**Issue by Arregator** [jupyterlab/debugger#371]
Hi, 

I am running JupyterLab 1.2.6 on Windows 10 Pro 64bit, **conda 4.7.12**. 

JupyterLab runs ok.

I am trying to install the extention with:

```
#ok
conda install nodejs xeus-python ptvsd

#fails
jupyter labextension install @jupyterlab/debugger
```

trace back is following:
```

Traceback (most recent call last):
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab_server\server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: Module not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<username>\Anaconda3\envs\jlab\Scripts\jupyter-labextension-script.py", line 5, in <module>
    from jupyterlab.labextensions import main
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab\labextensions.py", line 16, in <module>
    from .commands import (
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab\commands.py", line 28, in <module>
    from jupyterlab_server.process import which, Process, WatchHelper, list2cmdline
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "C:\Users\<username>\Anaconda3\envs\jlab\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'

```

it is fairly fresh environment, just in case it may help, my **conda list** :

```
conda list
# packages in environment at C:\Users\<username>\Anaconda3\envs\jlab:
#
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen
absl-py                   0.9.0                    py37_0
asn1crypto                1.3.0                    py37_0
astor                     0.8.0                    py37_0
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py37_0
beautifulsoup4            4.8.2                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blinker                   1.4                      py37_0
ca-certificates           2020.1.1                      0
cachetools                3.1.1                      py_0
certifi                   2019.11.28               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
colorama                  0.4.3                      py_0
cryptography              2.8              py37h7a1dbc1_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
gast                      0.2.2                    py37_0
google-auth               1.11.2                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.1.8                      py_0
grpcio                    1.27.2           py37h351948d_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.8                      py37_0
importlib_metadata        1.5.0                    py37_0
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
jedi                      0.15.2                   py37_0
jinja2                    2.11.1                     py_0
joblib                    0.14.1                     py_0
json5                     0.9.1                      py_0
jsonschema                3.2.0                    py37_0
jupyter_client            5.3.4                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.6              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
keras                     2.3.1                         0
keras-applications        1.0.8                      py_0
keras-base                2.3.1                    py37_0
keras-preprocessing       1.1.0                      py_1
libprotobuf               3.11.4               h7bd577a_0
libsodium                 1.0.17               h2fa13f4_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
nodejs                    10.13.0                       0
notebook                  6.0.3                    py37_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
oauthlib                  3.1.0                      py_0
openssl                   1.1.1d               he774522_4
opt_einsum                3.1.0                      py_0
pandas                    1.0.1            py37h47e9c7a_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.6.1                      py_0
pickleshare               0.7.5                    py37_0
pip                       20.0.2                   py37_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
protobuf                  3.11.4           py37h33f27b4_0
ptvsd                     4.3.2            py37hfa6e2cd_0    conda-forge
py4j                      0.10.7                   py37_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycparser                 2.19                     py37_0
pygments                  2.5.2                      py_0
pyjwt                     1.7.1                    py37_0
pyopenssl                 19.1.0                   py37_0
pyreadline                2.1                      py37_1
pyrsistent                0.15.7           py37he774522_0
pysocks                   1.7.1                    py37_0
pyspark                   2.4.5                      py_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3              py37he774522_0
pyzmq                     18.1.1           py37ha925a31_0
qgrid                     1.1.1                    py37_2    anaconda
requests                  2.22.0                   py37_1
requests-oauthlib         1.3.0                      py_0
rsa                       4.0                        py_0
scikit-learn              0.22.1           py37h6288b17_0
scipy                     1.4.1            py37h9439919_0
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
six                       1.14.0                   py37_0
soupsieve                 1.9.5                    py37_0
sqlite                    3.31.1               he774522_0
tensorboard               2.1.0                     py3_0
tensorflow                2.1.0           eigen_py37hd727fc0_0
tensorflow-base           2.1.0           eigen_py37h49b2757_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tornado                   6.0.3            py37he774522_3
traitlets                 4.3.3                    py37_0
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.1                     py_0
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xeus                      0.23.5               h1ad3211_0    conda-forge
xeus-python               0.6.11           py37h1ad3211_0    conda-forge
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_3

```

Any help will be appreciated.

Thank you,
Roman.

**Comment by SylvainCorlay** [comment]
Hey @Arregator by any chance, are you mixing with pip packages?

One thing I would recommend is getting pyzmq from the conda-forge channel instead of default, since zmq is from the conda-forge channel.

**Comment by Arregator** [comment]
Hi, @SylvainCorlay , thanks a lot for looking into this issue quickly!

I am not using pip for managing my environment, **conda** only.

Nevertheless your suggestion to install **pyzmq** from the **conda-forge** channel worked just great! 

I was able to 

`jupyter labextension install @jupyterlab/debugger`

without any errors now.

Thank you and have a good day!
Roman.
