### ISSUE TITLE
I can't install xeus-python with conda.

### ISSUE THREAD

**Issue by BigaMachine** [jupyterlab/debugger#384]
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: - failed with initial frozen solve. Retrying with flexible solve.
> 
> CondaError: KeyboardInterrupt
> 

It blocked permanently when I install xeus-python.
What should I do? Thanks! :)
And I have installed @jupyterlab/debugger successfully, but nothing changed..

envs: Ubuntu 19.10, Anaconda 2019.10, conda 4.7.12.

**Comment by afshin** [comment]
Is this the command you ran to install it?
```
conda install -c conda-forget xeus-python ptvsd
```

It needs to be the `conda-forge` channel. And you also need `ptvsd`.

**Comment by afshin** [comment]
(I edited the above because I had a typo.)

**Comment by BigaMachine** [comment]
Thanks for your reply :)
The command described in README.md that `conda install -c conda-forge xeus-python=0.6.7 notebook>=6 ptvsd` actually create  a "=6" file in my home folder. (This confused me a lot..)
So my command is `conda install -c conda-forge xeus-python=0.6.7 ptvsd`, since I found notebook has been installed in version 6.0.1 . 
And then an error described above occured.   :(

**Comment by afshin** [comment]
Okay, just drop the `=0.6.7` part and I think it should work for you. We need to update the README.

**Comment by afshin** [comment]
I think the trouble is that when you add constraints to arguments they need to be wrapped in quotation marks.

**Comment by BigaMachine** [comment]
I'm not sure whether it would be working, cause a slash is spinning round and round and round when I try to install xeus-python solely without any other constraint.`conda install -c conda-forge xeus-python`

**Comment by afshin** [comment]
Could you try running:
```
conda install --verbose -c conda-forge xeus-python
```
And paste the entire output of the command here?

**Comment by BigaMachine** [comment]
Sure, I run this and it exhausted all my cpu until I press `Control^C`, and get nothing.

```bash
(base) bgmc@tp:~$ conda install --verbose -c conda-forge xeus-python
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... ^Cfailed with initial frozen solve. Retrying with flexible solve.
Traceback (most recent call last):
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
    return func(*args, **kwargs)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 752, in _run_sat
    self.specs_to_add) or [])
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 1071, in get_conflicting_specs
    explicit_specs=explicit_specs)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/logic.py", line 923, in minimal_unsatisfiable_subset
    if sat(working_set | {spec, }, True) is None:
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 1059, in mysat
    return C.sat(constraints, add_if)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/logic.py", line 756, in sat
    solution = self._run_sat(self.m, limit=limit)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/logic.py", line 718, in _run_sat
    solution = self._sat_solver.run(m, limit=limit)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/logic.py", line 176, in run
    sat_solution = self.invoke(solver)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/common/logic.py", line 209, in invoke
    sat_solution = next(iter_sol)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bgmc/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1366, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1077, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1117, in handle_exception
    self._print_conda_exception(CondaError("KeyboardInterrupt"), _format_exc())
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1128, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1042, in print_conda_exception
    print(_format_exc(exc_val, exc_tb), file=sys.stderr)
  File "/home/bgmc/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1064, in _format_exc
    formatted_exception = format_exception(exc_type, exc_val, exc_tb)
  File "/home/bgmc/anaconda3/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/home/bgmc/anaconda3/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/home/bgmc/anaconda3/lib/python3.7/traceback.py", line 344, in extract
    for f, lineno in frame_gen:
  File "/home/bgmc/anaconda3/lib/python3.7/traceback.py", line 309, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'str' object has no attribute 'tb_frame'

```

**Comment by BigaMachine** [comment]
The environment is clean cause I reinstalled anaconda TwIcE.

**Comment by afshin** [comment]
Hm, I can't tell if this is a `conda` error or something that is wrong with `xeus-python`. Could you please post your log out put above into a new issue in the `xeus-python` repo?

https://github.com/jupyter-xeus/xeus-python/issues/new

And please link back to this issue as well. Perhaps the `xeus-python` will have more insight into how to solve this.

**Comment by BigaMachine** [comment]
You're right, this seems not a fault to @jupyterlab/debugger.
However, thanks for your time :)

**Comment by BigaMachine** [comment]
Succefully installed @jupyterlab/debugger! :)

The problem was induced by conda who can NOT correctly solve the **package conflicts**.

To solve this, I removed anaconda and installed **miniconda**, which is the minimal installer for conda, so that there won't be other packages interfare the installation of @jupyterlab/debugger.

Or, just create a new **CLEAN** virtual environment.

And, I think @jupyterlab/debugger is a critical feature to jupyterlab, and **SHOULD** work nicely in Anaconda cause it's a very popular distribution, but I don't know how :(

**Comment by martinRenou** [comment]
I suppose it should work with anaconda. As long as you only use the `conda-forge` channel.

**Comment by BigaMachine** [comment]
Yes, it works with `conda-forge`.
However, it's somehow strange to switch environment to use @jupyterlab/debugger, which can't be installed in the base environment.

**Comment by SylvainCorlay** [comment]
I think that the default channel has some conflicts with conda-forge.

I generally discourage people from using the full anaconda distribution for that reason. Starting with a miniconda instead and defaulting to conda-forge generally gives better results.
