### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jmrichardson** [jupyterlab/debugger#403]
Hi, I am trying to install on Windows 10 and got the following error message:

jupyter labextension install @jupyterlab/debugger
_cffi_ext.c
D:\Anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(266): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "D:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "D:\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "D:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "D:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "D:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "D:\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\jupyter-labextension-script.py", line 5, in <module>
    from jupyterlab.labextensions import main
  File "D:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 16, in <module>
    from .commands import (
  File "D:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 29, in <module>
    from jupyterlab_server.process import which, Process, WatchHelper, list2cmdline
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'

(base) D:\Projects>

I tried installing the jupyter_server but then it complained about:

ModuleNotFoundError: No module named 'jupyter_server.extensions'

I didn't install that one because these look like they are associated with jupyter and not jupyterlab.  What am i doing wrong?

**Comment by jtpio** [comment]
Thanks @jmrichardson for reporting this.

Did you also install the conda packages?

```
conda install -c conda-forge xeus-python=0.6.12 notebook=6 ptvsd
```

**Comment by jmrichardson** [comment]
Hi, Thanks for the quick response.  Here is what I have done:

```
conda install -c conda-forge jupyterlab
conda install -c conda-forge nodejs xeus-python=0.6.12 ptvsd
jupyter labextension install @jupyterlab/debugger
```

I just tried your recommendation which includes notebook=0.6.12:
```

(base) D:\Projects>conda install -c conda-forge xeus-python=0.6.12 notebook=6 ptvsd
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\Anaconda3

  added / updated specs:
    - notebook=6
    - ptvsd
    - xeus-python=0.6.12


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    notebook-6.0.3             |           py37_0         7.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.7 MB

The following NEW packages will be INSTALLED:

  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m

The following packages will be UPDATED:

  conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
  certifi              pkgs/main::certifi-2019.11.28-py37_1 --> conda-forge::certifi-2019.11.28-py37hc8dfbb8_1
  notebook                                        pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1e-he774522_0 --> conda-forge::openssl-1.1.1e-hfa6e2cd_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
notebook-6.0.3       | 7.7 MB    | ################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\python.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\python.exe', 'D:\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Anaconda3\python.exe, args are ['D:\\Anaconda3\\cwp.py', 'D:\\Anaconda3', 'D:\\Anaconda3\\python.exe', 'D:\\Anaconda3\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
done

(base) D:\Projects>jupyter labextension install @jupyterlab/debugger
_cffi_ext.c
D:\Anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(266): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "D:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "D:\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "D:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "D:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "D:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "D:\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\jupyter-labextension-script.py", line 5, in <module>
    from jupyterlab.labextensions import main
  File "D:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 16, in <module>
    from .commands import (
  File "D:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 29, in <module>
    from jupyterlab_server.process import which, Process, WatchHelper, list2cmdline
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "D:\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'
```

Thank you for your help

**Comment by jtpio** [comment]
It looks like something went wrong when installing `jupyterlab`.

Would it be possible to try in a new environment?

```
conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 ptvsd jupyterlab=2
conda activate jupyterlab-debugger
jupyter labextension install @jupyterlab/debugger --debug
```

**Comment by jmrichardson** [comment]
Thank you so much!  That was it.  The new environment resolved the problem.

**Comment by jtpio** [comment]
Perfect!

Yes in general it's better to stay away from the `base` environment and create new ones instead.

**Comment by tdalis** [comment]
This solution is not working for me in November 2021. Also, I am curious whether admin permissions on the computer are needed as I am trying to use Jupyter Lab on my work VM. Although, I don't understand why this would be an issue since I am trying to use it from an environment that I created and I install jupyter lab in it (I even created a second environment to test if the approach in this post would solve the issue). Any ideas or direction would be very helpful :)
