### ISSUE TITLE
cannot install the debugger

### ISSUE THREAD

**Issue by seyeeet** [jupyterlab/debugger#535]
hi 
im trying to use your debugger with jupyter lab
Im on Ubuntu 16.04

```
jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : 4.7.6
ipython          : 7.12.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```
I installed `conda install nodejs` and now I want to install your debugger.

In terminal, when I do `jupyter labextension install @jupyterlab/debugger` I see
```
Fail to get yarn configuration. /home/sey/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:1175
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

An error occured.
ValueError: Please install nodejs >=10.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-2a1bekk7.log
```
I am not sure why, but every time I install nodejs I see:
```
(base) sey@sey:~$ conda  install nodejs
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/sey/anaconda3

  added / updated specs:
    - nodejs

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nodejs-10.13.0             |       he6710b0_0        13.0 MB
    ------------------------------------------------------------
                                           Total:        13.0 MB

The following NEW packages will be INSTALLED:

  nodejs             pkgs/main/linux-64::nodejs-10.13.0-he6710b0_0
Proceed ([y]/n)? y
Downloading and Extracting Packages
nodejs-10.13.0       | 13.0 MB   | ############################################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
and then I want to check it but I see:
```
(base) sey@sey:~$ nodejs --version
The program 'nodejs' is currently not installed. You can install it by typing:
sudo apt install nodejs
```
If I go with `sudo apt install nodejs` the version is less than 10.

can you help me out, please?

**Comment by jtpio** [comment]
@seyeeet have you tried installing everything in a separate conda environment using the `conda-forge` channel?

There are some details in the README that should help fixing these kind of issues: https://github.com/jupyterlab/debugger#installation
