### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BernieTGN** [jupyterlab/debugger#546]
Hi, 
I am trying to install on Windows 10 with the following statements:

`conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.8.0 notebook=6 jupyterlab=2 ptvsd nodejs`
`conda activate jupyterlab-debugger`
`jupyter labextension install @jupyterlab/debugger`

but I got the following error message:

"_(jupyterlab-debugger) C:\Users\Patricia>jupyter labextension install @jupyterlab/debugger
Traceback (most recent call last):
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab_server\server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\notebook\notebookapp.py", line 51, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\Scripts\jupyter-labextension-script.py", line 5, in <module>
    from jupyterlab.labextensions import main
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\labextensions.py", line 16, in <module>
    from .commands import (
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\commands.py", line 29, in <module>
    from jupyterlab_server.process import which, Process, WatchHelper, list2cmdline
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "C:\Users\Patricia\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'

(jupyterlab-debugger) C:\Users\Patricia>_"

I would appreciate your help to know what I am doing wrong.

Thanks,

**Comment by jtpio** [comment]
>  ModuleNotFoundError: No module named 'jupyter_server'

It looks like an issue when creating the environment?

As an alternative we would suggest using the 3.0 release of JupyterLab, which now includes the debugger by default.

Installation steps are also simplified and don't require `nodejs`:

```bash
conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.9 jupyterlab=3
conda activate jupyterlab-debugger
```
